### ISSUE TITLE
Hangs on `ls` call

### ISSUE THREAD

**Issue by Xe** [astrada/google-drive-ocamlfuse#65] opened 2014-05-03 16:32 UTC
Running `ls` on the google drive mounted folder causes the filesystem to hang, usually forcing a reboot to fix.

**Comment by astrada** [comment] 2015-01-16 14:16
I'm closing this issue because there was no follow-up.

**Closed by astrada** 2015-01-16 14:16 UTC
Labels: question

**Comment by ewnjtgouierg** [comment] 2019-03-26 16:51
this is a very old topic, but since I have the exactly same issue, I comment here

I experience this problem on ubuntu 16.04

I use printf '%s\n' * as a workaround - it works fine
unlike the ls, which freezes, probably because it wants to load file attributes, not just file list
after that it can only be killed with kill -9

I ran gdo with -debug option, there was no any explicit error message, but may be log can tell you something, so here it is

gdo1.txt is when I start google-drive-ocamlfuse, cd to the mount point and run printf "%s\n" *
gdo2.txt is when I run ls

[gdo1.txt](https://github.com/astrada/google-drive-ocamlfuse/files/3009238/gdo1.txt)
[gdo2.txt](https://github.com/astrada/google-drive-ocamlfuse/files/3009240/gdo2.txt)

**Comment by astrada** [comment] 2019-03-26 20:49
It looks like you have many Google Docs in your directory. The problem is that Google Docs must be downloaded fully just to get their size. That's because you cannot download them in their original format, but they must be exported in some other (ods, doc, etc.). As a workaround (if you don't need them) you can stop downloading them with `download_docs=false` in your config. This should speed up things a lot.

**Comment by ewnjtgouierg** [comment] 2019-03-27 10:22
Thank you very much for your help
I added `download_docs=false` and ls works fine now
