### ISSUE TITLE
google-drive-ocamlfuse 100%cpu usage

### ISSUE THREAD

**Issue by deajan** [astrada/google-drive-ocamlfuse#171] opened 2016-04-08 07:51 UTC
Hello,

I'm using google-drive-ocamlfuse to backup about 300GB drive content via rsync.
After about an hour or so, the main google-drive-ocamlfuse process eats up a whole cpu core, and rsync doesn't do anything anymore.

I've tried single and mutlithreaded behavior, same issue.

Where should I begin to search for the problem ?
~/.gdfuse/gdfuse.log is empty

[EDIT]To get more accurate data, I've launched with

```
google-drive-ocamlfuse -debug -d /mnt/googledrive > /var/log/gdfuse_gd.log 2>&1 &
```

[/EDIT]

Config:

```
async_upload=false
client_id=
client_secret=
conflict_resolution=server
connect_timeout_ms=5000
curl_debug_off=false
debug=false
delete_forever_in_trash_folder=false
docs_file_extension=true
document_format=odt
document_icon=
download_docs=true
drawing_format=png
drawing_icon=
force_docs_export=true
form_format=ods
form_icon=
keep_duplicates=false
large_file_threshold_mb=16
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=2048
max_download_speed=0
max_retries=10
max_upload_speed=0
metadata_cache_time=1800
new_revision=true
presentation_format=pdf
presentation_icon=
read_only=true
spreadsheet_format=ods
spreadsheet_icon=
sqlite3_busy_timeout=100
stream_large_files=false
umask=0o022
verification_code=
```

Running version 0.5.22.

Thanks for any advice.

**Comment by astrada** [comment] 2016-04-08 08:06
To enable logging in `~/.gdfuse/default/gdfuse.log` you should use `-verbose`. Probably there are issues connecting to the Drive API endpoint and there are many retries (and if you enable logging you should see them).

**Comment by deajan** [comment] 2016-04-08 08:36
Should I leave -debug and -d too or only -verbose ?

**Comment by astrada** [comment] 2016-04-08 09:04
If you transferring 300GB, you shouldn't use `-debug`, because it will dump every transferred byte to `curl.log`. `-d` enables FUSE debugging mode (that doesn't log anything to the file-system, so you can turn it on, if you want, but it's not needed).

**Comment by deajan** [comment] 2016-04-08 09:13
Thanks, I'll report back when I have something strange in the logs.

**Comment by deajan** [comment] 2016-04-18 08:19
It seems that with -headless flag, I don't get 100% cpu usage.

**Closed** 2017-01-03 14:32 UTC
Labels: question

**Comment by daveiro** [comment] 2022-12-16 11:42
Hi, I am having this 100% cpu usage issue. Started google-drive-ocamlfuse both in normal and headless mode and the issue is still there. Using version google-drive-ocamlfuse-0.7.27 on Fedora 36. Transfer speed is erratic and slow, averaging on 400 Kb/s. Using standard gnome online account connectivity, I get speeds of 2MB/s. I didn't change anything in config file for now, settings follow below. Any idea on how to debug/solve this? Thanks!

acknowledge_abuse=false
apps_script_format=desktop
apps_script_icon=
async_upload_queue=false
async_upload_queue_max_length=0
async_upload_threads=10
autodetect_mime=true
background_folder_fetching=false
cache_directory=
client_id=
client_secret=
connect_timeout_ms=5000
curl_debug_off=false
data_directory=
debug_buffers=false
delete_forever_in_trash_folder=false
desktop_entry_as_html=false
desktop_entry_exec=
disable_trash=false
docs_file_extension=true
document_format=desktop
document_icon=
download_docs=true
drawing_format=desktop
drawing_icon=
form_format=desktop
form_icon=
fusion_table_format=desktop
fusion_table_icon=
keep_duplicates=false
large_file_read_only=false
large_file_threshold_mb=16
log_directory=
log_to=
lost_and_found=false
low_speed_limit=0
low_speed_time=0
map_format=desktop
map_icon=
max_cache_size_mb=512
max_download_speed=0
max_memory_cache_size=10485760
max_retries=8
max_upload_chunk_size=1099511627776
max_upload_speed=0
memory_buffer_size=1048576
metadata_cache_time=60
metadata_memory_cache=true
metadata_memory_cache_saving_interval=30
mv_keep_target=false
presentation_format=desktop
presentation_icon=
read_ahead_buffers=3
read_only=false
redirect_uri=
root_folder=
scope=
service_account_credentials_path=
service_account_user_to_impersonate=
spreadsheet_format=desktop
spreadsheet_icon=
sqlite3_busy_timeout=5000
stream_large_files=false
team_drive_id=
umask=0o002
verification_code=
write_buffers=false
