### ISSUE TITLE
Files added to Google drive folder (from others or the web interface) do not show up in local folder.

### ISSUE THREAD

**Issue by AndreRisnes** [astrada/google-drive-ocamlfuse#524] opened 2019-02-08 13:56 UTC
```
google-drive-ocamlfuse, version 0.7.1
Ubuntu 16.04.5 LTS
```

Hi,

I have a problem getting files from the remote drive to show up in my local folder. This is a simple way to reproduce it for me:

1. Mount an empty Google drive folder (root_folder=X) using `google-drive-ocamlfuse -cc -debug <local-folder>` (or just `google-drive-ocamlfuse <local-folder>`)
2. Go into the local folder and list contents. Only .Trash is shown.
3. Upload a file to the drive folder using the web interface
4. Wait a few minutes
5. List the local folder. No files show up (except .Trash).

See https://pastebin.com/HRKWsG2b for gdfuse.log, and https://pastebin.com/BXB7KLUW for curl.log

Possibly related to https://github.com/astrada/google-drive-ocamlfuse/issues/525

**Comment by astrada** [comment] 2019-02-09 14:31
Duplicate of #523

**Comment by astrada** [comment] 2019-02-09 15:29
Should be fixed in 0.7.2 that I just uploaded to my [beta ppa](https://launchpad.net/~alessandro-strada/+archive/ubuntu/google-drive-ocamlfuse-beta).

**Comment by AndreRisnes** [comment] 2019-02-11 09:04
That was fast! 0.7.3 seems to work fine on my machine now, thank you.

**Closed** 2019-02-13 17:04 UTC
Labels: duplicate
