### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by ovel2clock** [astrada/google-drive-ocamlfuse#60] opened 2014-04-04 14:39 UTC
First off, I love this!  This is exactly what I was looking for for Plex.  

I was able to successfully connect to my google drive using the steps listed out on GitHub and I was able to upload/download files.However, after some time, it drops the connection telling me the transport endpoint is not connected.   I've tried remounting with no luck.  

Here's what gdfuse.log shows :
[0.000638] TID=0: Setting up default filesystem...
[0.000676] TID=0: Loading configuration from /home/user/.gdfuse/default/config...done
Saving configuration in /home/user/.gdfuse/default/config...done
[0.001157] TID=0: Loading application state from /home/user/.gdfuse/default/state...done
Current version: 0.5.3
Setting up cache db...done
Setting up CURL...done
Refresh token already present.
[0.004306] TID=0: Starting filesystem /mnt/gdrive/
[0.015072] TID=0: init_filesystem
[35.449524] TID=0: getattr /
Loading metadata from db...not valid
Refreshing metadata...Refreshing access token...fail (error_code=Exception)
Error refreshing access token (try=0):
Exception:GaeProxy.ServerError("error_code Exception")
Backtrace:
fail (error_code=Exception)
Error refreshing access token (try=1):
Exception:GaeProxy.ServerError("error_code Exception")
Backtrace:
fail (error_code=Exception)

If I remove the .gdfuse directory and start over, it works again until it drops again after some time.  

Any ideas?  Thanks in advance!

**Comment by astrada** [comment] 2015-01-16 14:15
Closing as duplicate of #106.

**Closed by astrada** 2015-01-16 14:15 UTC
Labels: bug, duplicate

**Comment by JoseFMP** [comment] 2018-10-02 02:09
I do not see why it's duplicated of #106.

In any case, it's still happening. Ubuntu 18.04, google-drive-ocamlfuse, version 0.7.0
Any workarounds? It's a pity as this was the only decent solution to sync with google drive from ubuntu.
