### ISSUE TITLE
Add inotify interface

### ISSUE THREAD

**Issue by pisto** [astrada/google-drive-ocamlfuse#267] opened 2017-03-06 16:41 UTC
It would be great to have the [change notifications](https://developers.google.com/drive/v3/web/manage-changes) working. On top of that, one could also implement [inotify on fuse](https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE). See also #266

**Comment by astrada** [comment] 2017-03-06 21:14
Closing as duplicate of #230.

**Closed by astrada** 2017-03-06 21:14 UTC
Labels: duplicate
