### ISSUE TITLE
directories screwing up

### ISSUE THREAD

**Issue by bayoumedic** [astrada/google-drive-ocamlfuse#306] opened 2017-05-21 05:32 UTC
some directories not recognized as directories.
running ls -l
drwxrwxr-x 2 jason jason 4096 May 20 21:30 That '70s Show
?????????? ? ? ? ? ? The 100
?????????? ? ? ? ? ? The Detour
drwxrwxr-x 2 jason jason 4096 May 19 02:42 The Exorcist

they seem fine in google drive though

if i mount the drive using rclone this does not happen.
also the drive is encrypted using encfs.   if the ls -l command is done on the encrypted folder it produces the same results

**Comment by astrada** [comment] 2017-05-21 19:32
You should turn on verbose logging with `-debug`. Then you can check curl.log to see what kind of error you are getting from Drive API (if you don't find anything, please send the log files to my personal email: alessandro.strada@gmail.com).

**Comment by enz1ey** [comment] 2017-05-25 13:14
This is the same behavior as my issue, #303. Problem occurs randomly with newly uploaded files and persists until remounting with -cc option.

**Comment by kdizzay** [comment] 2017-06-01 18:25
+1, let me turn on debugs and see if I can reproduce with new media. It's on and off so can't seem to reliably reproduce the issue but it happens maybe 6/10 times.

**Comment by astrada** [comment] 2017-08-09 08:12
Duplicate of #303.

**Closed by astrada** 2017-08-09 08:12 UTC
Labels: duplicate
