### ISSUE TITLE
[Feature request]: Mount your TeamDrives

### ISSUE THREAD

**Issue by rmartin-rp** [astrada/google-drive-ocamlfuse#339] opened 2017-08-07 11:06 UTC
Since Team Drives has been released I would love to be able to mount a Team Drive in my file system.
Do you think that can be a big problem to implement?

Thanks for all this!

**Comment by astrada** [comment] 2017-08-09 07:55
The problem is that this feature it's only available as part of G Suite, and I don't have a G Suite account.

**Comment by astrada** [comment] 2017-08-09 07:55
Closing as duplicate of #288.

**Closed by astrada** 2017-08-09 07:55 UTC
Labels: duplicate
