### ISSUE TITLE
my disk become full 100%

### ISSUE THREAD

**Issue by imannms** [astrada/google-drive-ocamlfuse#331] opened 2017-07-18 17:37 UTC
Hello, I'm using google-drive-ocamlfuse on debian 8. I use `rsync` to upload large file (3GB) to google drive. but, after 3x rsync mydisk become full 100%. 

> Filesystem      Size  Used Avail Use% Mounted on
> **/dev/dm-0        48G   48G   21M 100% /**
> udev             10M     0   10M   0% /dev
> tmpfs           201M  4.5M  196M   3% /run
> tmpfs           501M     0  501M   0% /dev/shm
> tmpfs           5.0M     0  5.0M   0% /run/lock
> tmpfs           501M     0  501M   0% /sys/fs/cgroup
> /dev/sda1       236M   33M  191M  15% /boot
> tmpfs           101M     0  101M   0% /run/user/1000

this is my config:
> apps_script_format=json
> apps_script_icon=
> async_upload=true
> cache_directory=
> client_id=my_client_id
> client_secret=my_client_secret
> connect_timeout_ms=5000
> curl_debug_off=false
> data_directory=
> delete_forever_in_trash_folder=false
> docs_file_extension=true
> document_format=odt
> document_icon=
> download_docs=true
> drawing_format=png
> drawing_icon=
> form_format=zip
> form_icon=
> fusion_table_format=desktop
> fusion_table_icon=
> keep_duplicates=false
> large_file_read_only=true
> large_file_threshold_mb=1
> log_directory=
> lost_and_found=false
> low_speed_limit=0
> low_speed_time=0
> map_format=desktop
> map_icon=
> max_cache_size_mb=512
> max_download_speed=0
> max_memory_cache_size=10485760
> max_retries=8
> max_upload_chunk_size=1099511627776
> max_upload_speed=0
> memory_buffer_size=1048576
> metadata_cache_time=60
> presentation_format=pdf
> presentation_icon=
> read_ahead_buffers=3
> read_only=true
> shared_with_me=false
> spreadsheet_format=ods
> spreadsheet_icon=
> sqlite3_busy_timeout=5000
> stream_large_files=true
> umask=0o022
> verification_code=

How to solve this?

**Comment by jody-frankowski** [comment] 2017-07-18 17:40
Have you checked `~/.gdfuse/default/cache`? Mine sometimes seems to fill up when transferring large files, even though `stream_large_files=true`.

**Comment by imannms** [comment] 2017-07-18 17:49
yes, I checked and delete them manually with `sudo rm -rf ~/.gdfuse/default/cache/*`
but my disk still 100%

**Comment by astrada** [comment] 2017-07-18 17:54
> Mine sometimes seems to fill up when transferring large files, even though stream_large_files=true

stream_large_files doesn't work when uploading.

> yes, I checked and delete them manually with sudo rm -rf ~/.gdfuse/default/cache/* but my disk still 100%

They are probably still being used. Unmounting/remounting should free the disk space.

**Comment by jody-frankowski** [comment] 2017-07-18 18:11
@astrada I see. Will there be an equivalent for uploading in the future? (sorry for the off-topic)

**Comment by imannms** [comment] 2017-07-18 18:18
Solved.
Cache is stored in `/root/[mountpoint]`, not `/home/user/[mountpoint]`.
(Before I only checked `/home/user/`.)
And after delete them manually, now my disk is free.
You can close this.
Thanks for your response.

**Comment by astrada** [comment] 2017-07-18 18:21
> Will there be an equivalent for uploading in the future? (sorry for the off-topic)

No, sorry. The problem is that Drive API only allows uploading whole files.

**Comment by jody-frankowski** [comment] 2017-07-18 18:25
@astrada I can understand that, but why would it be necessary for the file to be copied in the cache?

**Comment by astrada** [comment] 2017-07-18 19:40
Because that's how a FUSE driver works. When you copy a file from your local file-system to a FUSE file-system the operative system issues a sequence of calls: a mknod(2) to create the file, and a series of write(2)s that copies the file by block (of 4KB or 128KB). Eventually flush(2) and close(2) are called to end the copy process and close the target file. So I don't have a single operation that I can stream, but I have a lot of small operation involving file chunks that I have to cache before I can start the uploading process.

**Closed** 2017-07-20 06:39 UTC
Labels: question
