### ISSUE TITLE
segfault in libgcrypt using headless login

### ISSUE THREAD

**Issue by dpadgett** [astrada/google-drive-ocamlfuse#104] opened 2014-12-19 18:05 UTC
using ubuntu 12, astrada's ppa build:

$ ulimit -c unlimited
$ google-drive-ocamlfuse -headless -id <> -secret <> -label gdrive gdrive
Please, open the following URL in a web browser: <>
Please enter the verification code: <>
Segmentation fault (core dumped)

(gdb) bt
#0  0xb7185e3d in ?? () from /lib/i386-linux-gnu/libgcrypt.so.11
#1  0xb7186256 in ?? () from /lib/i386-linux-gnu/libgcrypt.so.11
#2  0xb718686b in ?? () from /lib/i386-linux-gnu/libgcrypt.so.11
#3  0xb7186407 in ?? () from /lib/i386-linux-gnu/libgcrypt.so.11
#4  0xb716a567 in ?? () from /lib/i386-linux-gnu/libgcrypt.so.11
#5  0xb7160734 in gcry_cipher_setkey () from /lib/i386-linux-gnu/libgcrypt.so.11
#6  0xb727e79b in ?? () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#7  0xb7200f82 in ?? () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#8  0xb720c265 in ?? () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#9  0xb720c821 in ?? () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#10 0xb720cef7 in ?? () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#11 0xb71f53cd in ?? () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#12 0xb71f89f0 in ?? () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#13 0xb71fa3cd in gnutls_handshake () from /usr/lib/i386-linux-gnu/libgnutls.so.26
#14 0xb7617b68 in ?? () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#15 0xb7618c41 in ?? () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#16 0xb7619014 in Curl_gtls_connect () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#17 0xb7619781 in Curl_ssl_connect () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#18 0xb75f1f7f in Curl_http_connect () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#19 0xb7602601 in Curl_protocol_connect () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#20 0xb76028ea in Curl_setup_conn () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#21 0xb760299e in Curl_connect () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#22 0xb760a311 in ?? () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#23 0xb760afc3 in curl_easy_perform () from /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
#24 0x08191a3e in ?? ()
#25 0x080f084b in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by astrada** [comment] 2015-01-11 09:42
Closing as duplicate of #106.

**Closed by astrada** 2015-01-11 09:42 UTC
Labels: duplicate
